# Generated by Django 6.0.3 on 2026-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='เลขห้อง')),
                ('floor', models.IntegerField(verbose_name='ชั้น')),
                ('room_type', models.CharField(default='สตูดิโอ', max_length=50, verbose_name='ประเภทห้อง')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคาเช่า/เดือน')),
                ('status', models.CharField(choices=[('available', 'ว่าง'), ('occupied', 'มีผู้เช่า'), ('booked', 'จองแล้ว'), ('maintenance', 'ซ่อมแซม')], default='available', max_length=20, verbose_name='สถานะ')),
            ],
        ),
    ]
