# Generated by Django 6.0.3 on 2026-03-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('phone', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('move_in_date', models.DateField(verbose_name='วันที่ย้ายเข้า')),
                ('is_active', models.BooleanField(default=True, verbose_name='ยังพักอยู่หรือไม่')),
                ('room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.room', verbose_name='ห้องพักที่เช่า')),
            ],
        ),
    ]
