# Generated by Django 6.0.3 on 2026-03-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50, verbose_name='บิลประจำเดือน (เช่น ม.ค. 2026)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดชำระรวม')),
                ('due_date', models.DateField(verbose_name='วันครบกำหนดชำระ')),
                ('status', models.CharField(choices=[('pending', 'รอชำระ'), ('paid', 'ชำระแล้ว'), ('overdue', 'เกินกำหนด')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.room', verbose_name='ห้องพัก')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.tenant', verbose_name='ผู้เช่า')),
            ],
        ),
    ]
