# Generated by Django 6.0.3 on 2026-03-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อแจ้งซ่อม')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังซ่อม'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แจ้ง')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.room', verbose_name='ห้องพัก')),
            ],
        ),
    ]
