# Generated by Django 6.0.3 on 2026-03-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_maintenancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=20, unique=True, verbose_name='เลขที่สัญญา')),
                ('contract_type', models.CharField(choices=[('lease', 'สัญญาเช่า (เข้าพักเลย)'), ('booking', 'จองห้องพัก')], max_length=20, verbose_name='ประเภทเอกสาร')),
                ('tenant_name', models.CharField(max_length=150, verbose_name='ชื่อผู้เช่า/ผู้จอง')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มต้น')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุด')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินมัดจำ/ประกัน')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม')),
                ('status', models.CharField(choices=[('active', 'กำลังเช่า (Active)'), ('expiring', 'ใกล้หมดอายุ'), ('pending', 'รอเซ็นสัญญา')], default='active', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.room', verbose_name='ห้องพัก')),
            ],
        ),
    ]
