# Generated by Django 6.0.3 on 2026-03-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_prev_meter', models.IntegerField(default=0)),
                ('water_curr_meter', models.IntegerField(default=0)),
                ('water_unit_price', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('elec_prev_meter', models.IntegerField(default=0)),
                ('elec_curr_meter', models.IntegerField(default=0)),
                ('elec_unit_price', models.DecimalField(decimal_places=2, default=7, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'ค้างชำระ'), ('paid', 'ชำระแล้ว')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.tenant')),
            ],
        ),
    ]
