# Generated by Django 6.0.3 on 2026-03-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สะดวกให้เข้าซ่อม'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='reporter',
            field=models.CharField(default='ไม่มีชื่อ', max_length=100, verbose_name='ผู้แจ้ง'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='urgency',
            field=models.CharField(choices=[('normal', 'ปกติ (ดำเนินการภายใน 1-3 วัน)'), ('urgent', 'ด่วน (ดำเนินการภายใน 24 ชั่วโมง)'), ('very_urgent', 'ด่วนมาก (ฉุกเฉิน)')], default='normal', max_length=20, verbose_name='ความเร่งด่วน'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังซ่อม'), ('waiting', 'รออะไหล่'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='หัวข้อปัญหา'),
        ),
    ]
