# Generated by Django 6.0.3 on 2026-03-27 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_maintenancerequest_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'เช็คอิน (Check-in)'), ('out', 'เช็คเอาท์ (Check-out)')], max_length=10, verbose_name='ประเภทรายการ')),
                ('transaction_date', models.DateTimeField(verbose_name='วันที่/เวลา')),
                ('water_meter', models.IntegerField(default=0, verbose_name='เลขมิเตอร์น้ำ')),
                ('electric_meter', models.IntegerField(default=0, verbose_name='เลขมิเตอร์ไฟ')),
                ('key_received', models.BooleanField(default=False, verbose_name='รับกุญแจแล้ว')),
                ('damage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='หักค่าเสียหาย')),
                ('refund_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เงินประกันที่คืน')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ/สภาพห้อง')),
                ('staff_name', models.CharField(default='Admin สมชาย', max_length=100, verbose_name='เจ้าหน้าที่')),
                ('status', models.CharField(choices=[('success', 'สำเร็จ'), ('pending', 'รอยืนยัน')], default='success', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.room', verbose_name='ห้องพัก')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.tenant', verbose_name='ผู้เช่า')),
            ],
        ),
    ]
