# Generated by Django 6.0.3 on 2026-03-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_checkinoutlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinoutlog',
            name='tenant',
        ),
        migrations.AddField(
            model_name='checkinoutlog',
            name='tenant_name',
            field=models.CharField(default='ไม่มีชื่อ', max_length=150, verbose_name='ชื่อผู้เช่า'),
            preserve_default=False,
        ),
    ]
